dist: travis_latest
group: edge
sudo: false
language: c
os: linux
script:
  - mkdir build && (cd build && cmake .. -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCPACK_GENERATOR="DEB" -DCPACK_PACKAGE_CONTACT="dummy" && cmake --build . && ctest -V && cpack ..)
